spring:
  application:
    name: webpos-products
  session:
    store-type: redis
  cache:
    type: redis
  data:
    redis:
      host: 114.212.85.112
      port: 6379
server:
  port: 8083
eureka:
  client:
    serviceUrl:
      defaultZone: http://webpos-discovery:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.uuid}

