services:
    webpos-carts:
        build: ./webpos-carts
        ports:
            -  "9001:9001"
        depends_on:
            - webpos-discovery
    webpos-counter:
        build: ./webpos-counter
        ports:
            - "8082:8082"
        depends_on:
            - webpos-discovery
    webpos-products:
        build: ./webpos-products
        ports:
            - "8083:8083"
        depends_on:
            - webpos-discovery
    webpos-gateway:
        build: ./webpos-gateway
        ports:
            - "8080:8080"
        depends_on:
            - webpos-discovery
    webpos-discovery:
        build:  ./webpos-discovery
        ports:
            - "8761:8761"