services:
    webpos-carts:
        build: ./webpos-carts
        ports:
            -  "9001:9001"
        cpus: 2.0
        depends_on:
            - webpos-discovery
    webpos-counter:
        build: ./webpos-counter
        cpus: 2.0
        scale: 1
        depends_on:
            - webpos-discovery
    webpos-products:
        build: ./webpos-products
        ports:
            - "8083:8083"
        cpus: 2.0
        depends_on:
            - webpos-discovery
    webpos-gateway:
        build: ./webpos-gateway
        ports:
            - "8080:8080"
        depends_on:
            - webpos-discovery
    webpos-discovery:
        build:  ./webpos-discovery
        ports:
            - "8761:8761"