spring:
  cloud:
    gateway:
      routes:
        - id: webpos-carts
          uri: lb://webpos-carts
          predicates:
            - Path=/carts/**
        - id: webpos-counter
          uri: lb://webpos-counter
          predicates:
            - Path=/counter/**
        - id: webpos-products
          uri: lb://webpos-products
          predicates:
            - Path=/product/**
  main:
    web-application-type: reactive
  application:
    name: webpos-gateway
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8001/}
eureka:
  client:
    serviceUrl:
      defaultZone: http://webpos-discovery:8761/eureka/
    registry-fetch-interval-seconds: 5
  instance:
    instance-id: ${spring.application.name}:${random.uuid}

logging:
  level:
    root: DEBUG